### ISSUE TITLE
Redesign web

### ISSUE THREAD

**Issue by rosclaritha** [phisoft/assetsware-web#10]
You can retrieve the logo from the following issues:
https://github.com/phisoft/assetsware-addons/issues/3

**Comment by elioralatri** [comment]
![image](https://user-images.githubusercontent.com/57578708/165912996-2a1b6751-3a36-4e63-8f1f-8bb6fb82542e.png)

**Comment by elioralatri** [comment]
![image](https://user-images.githubusercontent.com/57578708/165913085-7c2a25d2-38a6-43a4-a667-ee3da63adacd.png)

**Comment by elioralatri** [comment]
![Web capture_29-4-2022_165036_127 0 0 1](https://user-images.githubusercontent.com/57578708/165913452-0eeb3051-1934-440d-b38d-6600cc904641.jpeg)
