### ISSUE TITLE
Fix typo

### ISSUE THREAD

**Issue by rosclaritha** [phisoft/assetsware-web#15]
`Instanly` -> `Instantly`

![image](https://user-images.githubusercontent.com/30463117/168198672-a231a9d2-ae28-42a4-afe3-8dac52fa8286.png)

**Comment by elioralatri** [comment]
![Screenshot (577)](https://user-images.githubusercontent.com/57578708/170402301-798f6995-f910-4450-9759-0ffa3662e6c1.png)
