### ISSUE TITLE
Redesign header

### ISSUE THREAD

**Issue by rosclaritha** [phisoft/assetsware-web#17]
![image](https://user-images.githubusercontent.com/30463117/169729824-d6a617b0-57fb-445f-a0c0-74bc5d027283.png)

**Comment by russel0907** [comment]
## Redesign header 

![Screenshot 2022-05-23 at 19-10-08 Assetsware - Asset Tracking with QRCode](https://user-images.githubusercontent.com/94702093/169807270-2a33af6d-3ba2-4f18-aae6-a991a9104f04.png)
