### ISSUE TITLE
Redesign footer

### ISSUE THREAD

**Issue by rosclaritha** [phisoft/assetsware-web#19]
![image](https://user-images.githubusercontent.com/30463117/173291818-f22ac1ad-af83-4195-9934-49bc0f36d809.png)

**Comment by russel0907** [comment]
Redesign footer;

## web view;
![Screenshot 2022-06-13 at 15-42-10 Assetsware - Asset Tracking with QRCode](https://user-images.githubusercontent.com/94702093/173304584-c43bb020-58e3-4d16-8c96-58404c00d05b.png)


## mobile view;
![Screen Shot 2022-06-13 at 15 43 53-fullpage](https://user-images.githubusercontent.com/94702093/173304618-ca2036e3-63b4-486e-a993-12a6aab39e32.png)
