### ISSUE TITLE
Change header color

### ISSUE THREAD

**Issue by rosclaritha** [phisoft/assetsware-web#20]
Change the header background. The color background looks a bit dull.
![image](https://user-images.githubusercontent.com/30463117/173293907-f73aecca-04c4-4c41-90ab-f6f76e15615f.png)

**Comment by russel0907** [comment]
update header color;
- add fade animation on header
- update color gradient
- update header button effect upon hover 

## before
![Screenshot 2022-06-13 at 16-44-45 Assetsware - Asset Tracking with QRCode](https://user-images.githubusercontent.com/94702093/173315284-3a0489c8-3e32-41f1-8085-84c568f64d63.png)

## after
![Assetsware-Asset-Tracking-with-QRCode (1)](https://user-images.githubusercontent.com/94702093/173315167-dd18b0b2-c19e-4bf3-abd9-66c37cd68fd0.png)
