### ISSUE TITLE
Optimize SEO for website

### ISSUE THREAD

**Issue by rosclaritha** [phisoft/assetsware-web#23]

**Comment by russel0907** [comment]
**Update meta for website SEO**
![code](https://user-images.githubusercontent.com/94702093/178911711-12d104d0-cc65-4ae3-9d06-aa84deb3dcef.png)

Update missing image at the features section previously
![Screenshot 2022-07-14 at 14-03-38 QR Inventory System and Asset Tracking ASAP Systems](https://user-images.githubusercontent.com/94702093/178911949-d3034356-ddab-46b5-b62a-c20e6e971d0f.png)
