### ISSUE TITLE
Provide header redesign mockup

### ISSUE THREAD

**Issue by rosclaritha** [phisoft/assetsware-web#24]
Create a few mockup or samples for the header. Header needs to be redesigned.
![image](https://user-images.githubusercontent.com/30463117/178882937-41d009e7-d204-4ab3-be7f-3441ecc55957.png)

**Comment by russel0907** [comment]
@rosclaritha 

Mockup 1
![Screenshot 2022-07-15 at 11-42-01 QR Inventory System and Asset Tracking ASAP Systems](https://user-images.githubusercontent.com/94702093/179145872-d48d3317-fdc0-49de-a81d-b53e3185901a.png)

Mockup 2
![Screenshot 2022-07-15 at 10-51-18 QR Inventory System and Asset Tracking ASAP Systems](https://user-images.githubusercontent.com/94702093/179145902-181c2856-6df5-4703-918d-c92613db8374.png)

Mockup 3
![Screenshot 2022-07-15 at 11-21-25 QR Inventory System and Asset Tracking ASAP Systems](https://user-images.githubusercontent.com/94702093/179145935-9ed958e6-adb1-4409-a237-c1917b62aac4.png)

Mockup 4
![Screenshot 2022-07-15 at 10-40-13 QR Inventory System and Asset Tracking ASAP Systems](https://user-images.githubusercontent.com/94702093/179145960-4645bf93-da51-4fe8-a14b-4e0c38eb801e.png)
