### ISSUE TITLE
Change button color to fit with web theme color

### ISSUE THREAD

**Issue by rosclaritha** [phisoft/assetsware-web#25]
<img width="1609" alt="Screenshot 2022-07-14 at 10 12 27 AM" src="https://user-images.githubusercontent.com/30463117/178883146-8c05a895-3e79-46c8-b126-1b84ac7f6125.png">

**Comment by russel0907** [comment]
update the center hover button color on process section and also slide up hover button color

![Screenshot (397)](https://user-images.githubusercontent.com/94702093/179147946-6c470178-34dc-479e-bac7-4499c28911e5.png)
