### ISSUE TITLE
Redesign header 

### ISSUE THREAD

**Issue by rosclaritha** [phisoft/assetsware-web#28]
Use Mockup 1 from https://github.com/phisoft/assetsware-web/issues/24

**Comment by russel0907** [comment]
**Update background image for the hero section**

![Screenshot 2022-07-21 at 10-16-13 QR Inventory System and Asset Tracking ASAP Systems](https://user-images.githubusercontent.com/94702093/180115603-ed9a9ecd-b738-463b-aad1-fc44480d082d.png)
