### ISSUE TITLE
Adjust header title for mobile view

### ISSUE THREAD

**Issue by rosclaritha** [phisoft/assetsware-web#30]
Make title smaller. Give a few samples of the view for different font size.

<img width="429" alt="Screenshot 2022-08-02 at 2 59 23 PM" src="https://user-images.githubusercontent.com/30463117/182312116-01882be8-ad3b-42ee-b4a4-0b740839ea3f.png">

**Comment by russel0907** [comment]
@rosclaritha 

## Design 1
![Screenshot 2022-08-03 at 09-26-41 QR Inventory System and Asset Tracking ASAP Systems](https://user-images.githubusercontent.com/94702093/182506351-0702ecdf-5797-44f4-ac39-04ca732de740.png)

## Design 2
![Screenshot 2022-08-03 at 09-28-15 QR Inventory System and Asset Tracking ASAP Systems](https://user-images.githubusercontent.com/94702093/182506370-f5932677-3ec2-4f2a-966d-69df74e106ee.png)

## Design 3
![Screenshot 2022-08-03 at 09-45-09 QR Inventory System and Asset Tracking ASAP Systems](https://user-images.githubusercontent.com/94702093/182506402-0de995e6-d276-41d7-8d2d-7d38e04cb6a5.png)
