### ISSUE TITLE
Remove #[object Object] from link

### ISSUE THREAD

**Issue by rosclaritha** [phisoft/assetsware-web#5]
<img width="1203" alt="Screenshot 2022-03-31 at 2 41 46 PM" src="https://user-images.githubusercontent.com/30463117/160992573-e392d721-4296-4558-a5d9-82b1deafffb4.png">

**Comment by russel0907** [comment]
Remove #[object Object] from link;

![Screenshot (224)](https://user-images.githubusercontent.com/94702093/161214643-09299513-46e8-439b-ba7e-4f4e68b8c536.png)
