### ISSUE TITLE
Update new template content

### ISSUE THREAD

**Issue by rosclaritha** [phisoft/assetsware-web#9]
You can retrieve the AssetsWare logo through the following issue:
https://github.com/phisoft/assetsware-addons/issues/3

**Comment by Jaironlanda** [comment]
Template source code: 
[Marvel Free Website Template - Free-CSS.com.zip](https://github.com/phisoft/assetsware-web/files/8560259/Marvel.Free.Website.Template.-.Free-CSS.com.zip)

**Comment by Jaironlanda** [comment]
<img width="1440" alt="Screenshot 2022-04-27 at 9 43 26 AM" src="https://user-images.githubusercontent.com/7873044/165421431-4b3bd897-95db-4405-b6ee-9d8189ceb3f9.png">
